# https://jekyllrb.com/docs/step-by-step/09-collections/#configuration

# Site settings
title:          Dev Ari
baseurl:        ""
url:            "https://blog.devari.kr"
# url:            "http://arikim92.github.io"

# Google Analytics
google_analytics: UA—99582153-1

# Author
author:
  name:         Ari Kim
  url:          https://www.devari.kr
  email:        cherryad9282@gmail.com
  github:       arikim92

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks ( http://jekyllrb-ko.github.io/docs/permalinks/ )
permalink:     /:year/:categories/:title
paginate:      5
paginate_path: /page/:num

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
img_url: /assets/img
category_list: [ nodejs, javascript, tip, diary, linux, chatbot, php ,publishing, jekyll, sql, error ]

disqus: arikim #https://arikim.disqus.com/admin/settings/general/
